spring:
  application:
    name: ncsys_springboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ncsys_dev
    username: root
    password: 123456
#    为解决建表失败回滚而设计, 最后没有解决
#    hikari:
#      auto-commit: false
#  profiles:
#    active: dev

server:
  port: 8090
  servlet:
    context-path: /ncsys
    session:
      timeout: 3600 # Session超时时间（秒）
#    encoding: 该配置未能解决windows环境中文乱码问题
#      charset: UTF-8
#      force: true
#      enabled: true

jwt:
  secret-key: your-strong-secret-key-here # 至少32位随机字符串
  expiration: 3600 # 过期时间（秒）

# 开启 MyBatis-Plus SQL 日志（格式：控制台输出）
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 直接输出到控制台
  mapper-locations: classpath:/com/dc/ncsys_springboot/mapper/*/*.xml

logging:
  level:
    root: INFO
    org:
      springframework:
        transaction:
          interceptor: TRACE
        jdbc:
          datasource: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %clr(%-5level) %clr(%logger{36}){cyan} - %line : %replace(%msg){'\"avatar\":\".*?\"', '\"avatar\":\"[FILTERED]\"'}\n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %line : %replace(%msg){'\"avatar\":\".*?\"', '\"avatar\":\"[FILTERED]\"'}\n"
#  charset: 该配置未能解决windows环境中文乱码问题
#    console: UTF-8
#    file: UTF-8


