spring:
  application:
    name: ncsys_springboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ncsys_dev
    username: root
    password: 123456
server:
  port: 8090
  servlet:
    context-path: /ncsys


# 开启 MyBatis-Plus SQL 日志（格式：控制台输出）
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 直接输出到控制台